name: puls
services:
  - name: puls
    dockerfile_path: Dockerfile
    http_port: 8080
    envs:
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
    health_check:
      http_path: /?health
